#!/bin/bash

# Variables
vhostname=$1;
tier=$2

httpdconf=/etc/httpd/conf/httpd.conf
vhostconfdir=/etc/httpd/conf.vhosts.d
defvhostconffile=$vhostconfdir/00-default-vhost.conf
vhostconffile=$vhostconfdir/${vhostname}.conf
wwwroot=/srv
defvhostdocroot=$wwwroot/default/www
vhostdocroot=$wwwroot/$vhostname/www

# Validate input
if [ "$vhostname" = '' ] || [ "$tier" = '' ]; then
  echo "Usage: $0 vhostname tier";
  exit 1;
else

# Get support email address
  case $tier in
    1) vhostadmin='basic_support@example.com'
      ;;
    2) vhostadmin='business_support@example.com'
      ;;
    3) vhostadmin='enterprise_support@example.com'
      ;;
    *) echo 'Invalid tier specified'
       exit 1
       ;;
  esac
fi

# Create con directory if it does not exist
if [ ! -d $vhostconfdir ]; then
  mkdir $vhostconfdir
  if [ $? -ne 0 ]; then
    echo "ERROR-1: Failed creating ${vhostconfdir}."
    exit 1
  fi
fi

# Insure include statement exists in the /etc/httpd/conf/httpd.conf file
grep -q '^IncludeOptional conf\.vhosts\.d/\*\.conf$' $httpdconf

if [ $? -ne 0 ]; then
  #Backup before modifying
  cp -a $httpdconf $httpdconf.orig

  echo "IncludeOptional conf.vhosts.d/*.conf" >> $httpdconf

  if [ $? -ne 0 ]; then
    echo "Error-2: Failed adding include directive"
    exit 1
  fi
fi

# Check for default virtual host
if [ ! -f $defvhostconffile ]; then
  cat <<defconfeof > $defvhostconffile
<VirtualHost _default_:80>
  DocumentRoot $defvhostdocroot
  CustomLog 'logs/default-vhost.log' combined
</VirtualHost>

<Directory $defvhostdocroot>
  Require all granted
</Directory>
defconfeof
fi

# Verify that the default vhost doc root exists
if [ ! -d $defvhostdocroot ]; then
  mkdir -p $defvhostdocroot
  restorecon -Rv $wwwroot
fi

# Check for virtual host conflict
if [ -f $vhostconffile ]; then
  echo "ERROR-3: $vhostconffile already exists."
  exit 1
elif [ -d $vhostdocroot ]; then
  echo "ERROR-4: $vhostdocroot already exists"
  exit 1
else
  cat <<confeof >$vhostconffile
<Directory $vhostdocroot>
  Require all granted
  AllowOverride None
</Directory>

<VirtualHost *:80>
  DocumentRoot $vhostdocroot
  ServerName $vhostname
  ServerAdmin $vhostadmin
  ErrorLog "logs/${vhostname}_error_log"
  CustomLog "logs/${vhostname}_access_log" common
</VirtualHost>
confeof
  mkdir -p $vhostdocroot
  restorecon -Rv $wwwroot
fi

# Check config and reload
apachectl configtest &> /dev/null

if [ $? -eq 0 ]; then
  systemctl reload httpd &> /dev/null
else
  echo "ERROR-5: Config error."
  exit 1;
fi
